
### Update a product
PUT http://localhost:4000/products/7374e501-fc54-4c48-8105-2374403795ba
Content-Type: application/json

{
  "productName": "MacBook Air M3 - Updated",
  "description": "Updated description",
  "price": 1299.99,
  "discountedPrice": 1199.99,
  "quantityAvailable": 30,
  "dateAdded": "2025-09-18T10:00:00",
  "live": true,
  "inStock": true,
  "productImageName": "macbook_air_m3.png"
}
